### ISSUE TITLE
New channel follower causes bot to ping channel every 2 minutes 

### ISSUE THREAD

**Issue by ppphhhiiilll** [dblock/slack-arena#37] opened 2022-01-07 15:34 UTC
When a new user follows a connected Are.na, the bot will repeatedly ping the Slack channel in 2 minute intervals. 

As far as I can tell this only applies to new follows, not for any newly connected blocks.

**Comment by dblock** [comment] 2022-01-07 16:59
Looks like an auth error that's not handled.

```
W, [2022-01-07T16:57:57.148166 #242]  WARN -- : Error in cron for team name=.., id=..., account_inactive, /app/vendor/bundle/ruby/2.6.0/gems/slack-ruby-client-0.15.0/lib/slack/web/faraday/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/request/multipart.rb:25:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
/app/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
/app/vendor/bundle/ruby/2.6.0/gems/slack-ruby-client-0.15.0/lib/slack/web/faraday/request.rb:26:in `request'
/app/vendor/bundle/ruby/2.6.0/gems/slack-ruby-client-0.15.0/lib/slack/web/faraday/request.rb:11:in `post'
/app/vendor/bundle/ruby/2.6.0/gems/slack-ruby-client-0.15.0/lib/slack/web/api/endpoints/chat.rb:193:in `chat_postMessage'
/app/slack-arena/models/arena_feed.rb:122:in `block in sync!'
/app/slack-arena/models/arena_feed.rb:111:in `each'
/app/slack-arena/models/arena_feed.rb:111:in `sync!'
/app/slack-arena/models/arena_feed.rb:53:in `sync_new_arena_items!'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/association/referenced/has_many/proxy.rb:165:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/association/referenced/has_many/enumerable.rb:193:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:137:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/collection/view/iterable.rb:51:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:163:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:161:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:161:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/collection/view/iterable.rb:50:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/query_cache.rb:228:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:136:in `each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/association/referenced/has_many/enumerable.rb:189:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/association/referenced/has_many/proxy.rb:165:in `each'
/app/slack-arena/app.rb:79:in `block in sync!'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:710:in `yield_document'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:137:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/collection/view/iterable.rb:51:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:163:in `block in each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:161:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/cursor.rb:161:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongo-2.13.0/lib/mongo/collection/view/iterable.rb:50:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/query_cache.rb:228:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/mongoid-7.1.2/lib/mongoid/contextual/mongo.rb:136:in `each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/forwardable.rb:230:in `each'
/app/slack-arena/app.rb:76:in `sync!'
/app/slack-arena/app.rb:12:in `block (2 levels) in after_start!'
/app/slack-arena/app.rb:41:in `block (2 levels) in continuously'
/app/slack-arena/app.rb:40:in `loop'
/app/slack-arena/app.rb:40:in `block in continuously'
/app/vendor/bundle/ruby/2.6.0/gems/async-1.26.2/lib/async/task.rb:258:in `block in make_fiber'.
```

**Comment by dblock** [comment] 2022-01-07 17:28
With the fix the team above that had this error got disconnected as expected: @ppphhhiiilll reinstall the bot, let's see if this happens again?

**Comment by ppphhhiiilll** [comment] 2022-01-08 01:40
<img width="757" alt="Screen Shot 2022-01-07 at 8 38 53 PM" src="https://user-images.githubusercontent.com/41241831/148626537-d33df1a4-6d90-4f51-ae7c-b83da2c798d1.png">

It looks like it's still happening – note the pings at 8:36 PM and then the repeat at 8:38 PM.

**Comment by dblock** [comment] 2022-01-08 03:17
I made some progress. This is caused by adding a user to a group. The feed looks different from what I'd expect (item = null), so the code didn't anticipate that, worked around in https://github.com/dblock/slack-arena/commit/b1f2455501cf68e9fcd59d4c501ea39584f5f582. However the message is going to be incorrect. 

<img width="724" alt="Screen Shot 2022-01-07 at 10 15 40 PM" src="https://user-images.githubusercontent.com/542335/148629698-6092c41a-14ac-4ff2-8971-502035afbec0.png">

In the example above I added Cab to a group. 

I think this may be an are.na bug actually, I'll report it.

**Comment by dblock** [comment] 2022-01-08 03:47
The repeat messaging shouldn't happen again with https://github.com/dblock/slack-arena/commit/ce2761880c9c2a1fa48ed82416a6199bb71f98e0. 

I opened https://github.com/dblock/slack-arena/issues/40 and https://github.com/dblock/slack-arena/issues/39 for problems I found while debugging this.

I'm going to close this, but add on more comments/reopen if you're still seeing the repeat problem.

**Closed by dblock** 2022-01-08 03:47 UTC
